#!/bin/bash

echo redisp begins 2>&1 | tee -a log.txt

sort -n mpc3.txt |uniq  >  mpc4.txt 2>&1 | tee -a log.txt
redisp.py 2>&1 | tee -a log.txt
awk '{print($1,$2,$5,$6)}' predisp.txt > redisp.txt 2>&1 | tee -a log.txt

echo redisp ends 2>&1 | tee -a log.txt
