#!/bin/bash

set -o pipefail
echo redisp begins 2>&1 | tee -a log.txt

sort -n mpc3.txt |uniq  >  mpc4.txt 2>&1 | tee -a log.txt
echo $? 64 605 >> error.txt

redisp.py 2>&1 | tee -a log.txt

awk '{print($1,$2,$5,$6)}' predisp.txt | sort -k 1,1 -k 2n,2 > redisp.txt 2>&1 | tee -a log.txt
sort -n -o newall.txt newall.txt 2>&1 | tee -a log.txt
echo $? 64 607 >> error.txt

echo redisp ends 2>&1 | tee -a log.txt
