#!/bin/bash
#version 2021.6.17
cp send_mpc.txt hoge2.txt
deldaburi4.py
dos_find mpc7.txt -k > result.txt
delLargeZansa_and_modPrecision.py 1
komejirushi.py
reject_bright_known_asteroids_from_report.py
