#!/bin/bash
#all REVISED (2022.4.12 KS)
#convert to mpd to edb
#getMPCORB_and_mpc2edb /one time
# AstMPC.edb /onetime

haveAllPreciseOrbits=$(<./have_all_precise_orbits.txt)
if [ "$haveAllPreciseOrbits" = "0" ]; then
    sed  s/\'//g ~/.coias/param/AstMPC_dim.edb |sed -e '1,51d' > hoge
    #./getinfo_xephem.py > cand.txt
    searchB.py
    ## remove a character "\" from cand.txt
    sed -e 's/\\//g' cand.txt > cand2.txt  
    ## remove the asteroids whose magnitudes are larger than 30 mag (very faint asteroids)
    awk '$6<30 {print $0}' cand2.txt > cand2b.txt
    
    ## classify asteroids into two groups, numbered asteroids and those only having karifugo
    ## numbered (named) asteroids (2021.12.20 NM)
    awk -F" " '$2 ~ /^[1-9]/ && $3 ~ /^[A-Z]/ && $3 !~ /[A-Z][A-Z][0-9]*/ {print $2}' cand2b.txt > cand3.txt
    ## numbered (unnamed) asteroids (2021.12.20 NM)
    awk -F" " '$2 ~ /^[1-9]/ && $3 ~ /^[1-2]/ {print $2}' cand2b.txt >> cand3.txt
    ## karifugo asteroids (2021.12.20 NM)
    awk -F" " '$2 ~ /^[1-2]/ && $3 ~ /[A-Z][A-Z][0-9]*/ {print $2,$3}' cand2b.txt > cand4.txt
fi

#getinfo_numbered2B.py
#getinfo_karifugo2B.py
#REVISED 2020.1.28
#REVISED 2020.5.29 2B=>2D 
getinfo_numbered2D.py





getinfo_karifugo2D.py

#(cat numbered_new2B.txt karifugo_new2B.txt |sort -n >search_astB.txt) <- old statement, we did not use this from 2020/12
#Revised 2020.2.20
#grep -E "^19|^20" karifugo_new2B.txt > karifugo_new2C.txt 
#cat numbered_new2B.txt karifugo_new2C.txt |sort -n > search_astpre.txt
#REVISED 2020.2.2
#Revised 2020.2.20
#sed 's/--/30.0/g;' search_astpre.txt |sed 's/ (1999 19 //g;' |sed 's/ (1981 2 //g;'|sed 's/ - / /g;'> search_astB.txt
#Revised 2022.4.12 KS, I merged the above three statements to make_seach_astB_in_each_directory.py
make_search_astB_in_each_directory.py
