#!/bin/bash
#all REVISED (2022.4.28 KS)

haveAllPreciseOrbits=$(cat have_all_precise_orbits.txt )
if [ "$haveAllPreciseOrbits" = "0" ]; then
    sed  s/\'//g ~/.coias/param/AstMPC_dim.edb |sed -e '1,51d' > hoge
    sed  s/\'//g ~/.coias/param/AstMPC.edb |sed -e '1,51d' > AstMPC_tmp.edb
    #./getinfo_xephem.py > cand.txt <- old statement, we did not use this from 2020/12
    ## search known dim asteroids in the field and output to cand.txt
    searchB.py
    ## search konwn bright asteroids in the field and output to cand_bright.txt
    searchB_AstMPC.py
    ##merge
    cat cand_dim.txt cand_bright.txt > cand.txt
    ## remove a character "\" from cand.txt
    sed -e 's/\\//g' cand.txt > cand2.txt  
    ## remove the asteroids whose magnitudes are larger than 30 mag (very faint asteroids)
    awk '$6<30 {print $0}' cand2.txt > cand2b.txt
    
    ## classify asteroids into two groups, numbered asteroids and those only having karifugo
    ## numbered (named) asteroids (2022.4.18 KS)
    awk -F" " '$2 ~ /^[1-9]/ && $3 ~ /^[A-Z]/ && $3 !~ /[A-Z][A-Z][0-9]*/ && $3 != "P-L" && $3 != "T-1" && $3 != "T-2" && $3 != "T-3" {print $2}' cand2b.txt > cand3.txt
    ## numbered (unnamed) asteroids (2022.4.18 NM)
    awk -F" " '$2 ~ /^[1-9]/ && $3 ~ /^[1-2]/ || $4 == "P-L" || $4 == "T-1" || $4 == "T-2" || $4 == "T-3" {print $2}' cand2b.txt >> cand3.txt
    ## karifugo asteroids (2022.4.18 KS)
    awk -F" " '$2 ~ /^[1-2]/ && $3 ~ /[A-Z][A-Z][0-9]*/ || $3 == "P-L" || $3 == "T-1" || $3 == "T-2" || $3 == "T-3" {print $2,$3}' cand2b.txt > cand4.txt

    make_asteroid_name_list_in_the_field.py
fi

#getinfo_numbered2B.py
#getinfo_karifugo2B.py
#REVISED 2020.1.28
#REVISED 2020.5.29 2B=>2D 
getinfo_numbered2D.py

