#!/bin/bash
#version 2021.6.28 K.S.

if [ ! -d ~/.coias ]; then
    mkdir ~/.coias
    make_default_parameter_files.py
    getMPCORB_and_mpc2edb
else
    if [ ! -f ~/.coias/default.conv ]; then
	make_default_parameter_files.py
    fi

    if [ ! -f ~/.coias/MPCORB.DAT ]; then
	getMPCORB_and_mpc2edb
    fi
fi
