#!/bin/bash
#version 2022.4.12 K.S.

if [ ! -d ~/.coias ]; then
    mkdir ~/.coias
fi

if [ ! -d ~/.coias/param ]; then
    mkdir ~/.coias/param
fi

if [ ! -d ~/.coias/orbit_data ]; then
    mkdir ~/.coias/orbit_data
fi
    
if [ ! -f ~/.coias/param/default.conv ]; then
    make_default_parameter_files.py
fi

if [ ! -f ~/.coias/param/MPCORB.DAT ]; then
    getMPCORB_and_mpc2edb
fi
