#!/bin/bash
#timestamp: 2022/6/8 17:30 sugiura

error=0

if [ -e "mpc4_m.txt" ]; then
    cat mpc4.txt mpc4_m.txt | sort -n > mpc4_automanual.txt
    if [ $? -ne 0 ]; then
	error=1
    fi
else
    cat mpc4.txt | sort -n > mpc4_automanual.txt
    if [ $? -ne 0 ]; then
	error=1
    fi
fi

if [ -e "newall_m.txt" ]; then
    cat	newall.txt newall_m.txt | sort -n > newall_automanual.txt
    if [ $? -ne 0 ]; then
	error=1
    fi
else
    cat	newall.txt | sort -n > newall_automanual.txt
    if [ $? -ne 0 ]; then
        error=1
    fi
fi

if [ -e "redisp_manual.txt" ]; then
    cat redisp.txt redisp_manual.txt | sort -k 1,1 -k 2n,2 > redisp_automanual.txt
    if [ $? -ne 0 ]; then
	error=1
    fi
else
    cat redisp.txt | sort -k 1,1 -k 2n,2 > redisp_automanual.txt
    if [ $? -ne 0 ]; then
	error=1
    fi
fi

if [ -e "H_conversion_list_manual.txt" ]; then
    cat	H_conversion_list.txt H_conversion_list_manual.txt > H_conversion_list_automanual.txt
    if [ $? -ne 0 ]; then
	error=1
    fi
else
    cat	H_conversion_list.txt > H_conversion_list_automanual.txt
    if [ $? -ne 0 ]; then
        error=1
    fi
fi

exit $error
