#!/bin/bash
#Timestamp: 2022/08/04 11:30 sugiura
########################################################
# 内容はgetMPCORB_and_mpc2edbとほとんど同一であるが,
# GUI COIASの小惑星データ更新ボタンで叩かれるスクリプトはこれ.
# ボタンを叩かれたときに独立して動作するように,
# 無いディレクトリの作成とエラーハンドリングが追記してある.
########################################################

set -o pipefail
echo getMPCORB_and_mpc2edb_for_button begins 2>&1 | tee log.txt
. PARAM
echo $? 15 111 > error.txt

if [ ! -d "${COIAS_DATA_PATH}" ]; then
    mkdir "${COIAS_DATA_PATH}" 2>&1 | tee -a log.txt
    echo $? 15 112 >> error.txt
fi

if [ ! -d "${COIAS_DATA_PATH}/param" ]; then
    mkdir "${COIAS_DATA_PATH}/param" 2>&1 | tee -a log.txt
    echo $? 15 113 >> error.txt
fi

getMPCORB_and_mpc2edb 2>&1 | tee -a log.txt

echo getMPCORB_and_mpc2edb_for_button ends 2>&1 | tee -a log.txt

error_handling.py | tee -a log.txt
exit $?
