#!/bin/bash
#Timestamp: 2022/08/04 11:30 sugiura
#####################################################
# 1. MPCからMPCORB.DATをダウンロードし,
#    ~/.coias/paramに保存する.
# 2. mpc2edb.plを動かし, MPCORB.DATをedb形式に変換する.
#    AstMPC.edb: 15等級より明るくなることがある小惑星の情報
#    AstMPC_dim.edb: それ以外の暗い小惑星の情報
#    これら2つのファイルも~/.coias/paramに保存される.
#####################################################
. def_coias_data_path

wget -O "./MPCORB_TEMP.DAT" https://www.minorplanetcenter.net/iau/MPCORB/MPCORB.DAT
echo $? 12 107 >> error.txt

mv "./MPCORB_TEMP.DAT" "${COIASDATAPATH}/param/MPCORB.DAT"

mpc2edb.pl "${COIASDATAPATH}/param/MPCORB.DAT" "${COIASDATAPATH}"
echo $? 15 108 >> error.txt
