#!/bin/bash
#version 2022.5.6 K.S.

set -o pipefail
echo preprocess begins 2>&1 | tee log.txt
echo $? 15 101 > error.txt

if [ ! -d ~/.coias ]; then
    mkdir ~/.coias 2>&1 | tee -a log.txt
    echo $? 15 102 >> error.txt
fi

if [ ! -d ~/.coias/param ]; then
    mkdir ~/.coias/param 2>&1 | tee -a log.txt
    echo $? 15 103 >> error.txt
fi

if [ ! -d ~/.coias/orbit_data ]; then
    mkdir ~/.coias/orbit_data 2>&1 | tee -a log.txt
    echo $? 15 104 >> error.txt
    
    echo 0 > ~/.coias/orbit_data/log.txt 2>&1 | tee -a log.txt
    echo $? 15 105 >> error.txt
fi
    
if [ ! -f ~/.coias/param/default.conv ]; then
    make_default_parameter_files.py 2>&1 | tee -a log.txt
fi

if [ ! -f ~/.coias/param/MPCORB.DAT ]; then
    getMPCORB_and_mpc2edb 2>&1 | tee -a log.txt
else
    #even if MPCORB.DAT exists, interruption of previous download leads to incomplete data and we need re-download
    wget --spider https://www.minorplanetcenter.net/iau/MPCORB/MPCORB.DAT 2>&1 | tee wgetMPC.txt
    echo $? 12 109 >> error.txt

    MSIZE=`grep -oE "\([0-9]*M\)" wgetMPC.txt | sed "s/(//g" | sed "s/)//g" | sed "s/M//g"`
    MPCMSIZE=`ls -l ~/.coias/param/MPCORB.DAT | awk '{print $5 * 1.1 * 0.000001}' | awk '{printf("%d",$1)}'`
    if [ $MPCMSIZE -lt $MSIZE ]; then
	echo "previous download of MPCORB.DAT may be interrupted. download again." 2>&1 | tee -a log.txt
	getMPCORB_and_mpc2edb 2>&1 | tee -a log.txt
    fi
fi

echo preprocess ends 2>&1 | tee -a log.txt

error_handling.py | tee -a log.txt
exit $?
