#!/bin/bash
#Timestamp: 2022/08/04 18:00 sugiura
###########################################################################################
# COIAS.py以降の検出・解析をした後に, もう一度AstsearchRの探索準備をしたいこともあるかもしれないが,
# 再解析すると移動天体候補のHから始まる名前が全て変わってしまう.
# そのようなときに前回の解析で得たCOIAS.py以降のファイルが残っていると辻褄が合わなくなってしまうので,
# そのようなファイルを消去する.
###########################################################################################

error=0

if [ -e "memo.txt" ]; then
	rm memo.txt
	if [ $? -ne 0 ]; then
		error=1
    fi
fi

if [ -e "memo_manual.txt" ]; then
	rm memo_manual.txt
	if [ $? -ne 0 ]; then
		error=1
    fi
fi

if [ -e "mpc4.txt" ]; then
	rm mpc4.txt
	if [ $? -ne 0 ]; then
		error=1
    fi
fi

if [ -e "mpc4_m.txt" ]; then
	rm mpc4_m.txt
	if [ $? -ne 0 ]; then
		error=1
    fi
fi

if [ -e "mpc4_automanual.txt" ]; then
	rm mpc4_automanual.txt
	if [ $? -ne 0 ]; then
		error=1
    fi
fi

if [ -e "redisp.txt" ]; then
	rm redisp.txt
	if [ $? -ne 0 ]; then
		error=1
    fi
fi

if [ -e "redisp_manual.txt" ]; then
	rm redisp_manual.txt
	if [ $? -ne 0 ]; then
		error=1
    fi
fi

if [ -e "reredisp.txt" ]; then
	rm reredisp.txt
	if [ $? -ne 0 ]; then
		error=1
    fi
fi

if [ -e "H_conversion_list.txt" ]; then
	rm H_conversion_list.txt
	if [ $? -ne 0 ]; then
		error=1
    fi
fi

if [ -e "H_conversion_list_manual.txt" ]; then
	rm H_conversion_list_manual.txt
	if [ $? -ne 0 ]; then
		error=1
    fi
fi

if [ -e "manual_name_modify_list.txt" ]; then
	rm manual_name_modify_list.txt
	if [ $? -ne 0 ]; then
		error=1
    fi
fi

if [ -e "manual_delete_list.txt" ]; then
	rm manual_delete_list.txt
	if [ $? -ne 0 ]; then
		error=1
    fi
fi

if [ -e "manual_delete_list2.txt" ]; then
	rm manual_delete_list2.txt
	if [ $? -ne 0 ]; then
		error=1
    fi
fi

exit $error
