#!/bin/bash
#S.U made on 2021/7/14
#Timestamp: 2022/08/05 22:00 sugiura
##############################################################################################
# COIAS.pyのmanual measureモードでの手動測定を元にして,
# 1. photometry_manual_objects.py 測光する
# 2. match2E.py 手動測定点と既知天体の照合を行う
# 3. change_data_to_mpc_format_manual.py MPCフォーマットに変換する
# 4. make_mpc4_newall_and_redisp_manual.py 手動測定版のmpc4.txt, newall.txt, redisp.txtを作成する.
# GUI COIASの手動測定モードにて探索終了ボタンを押すとこのスクリプトが叩かれる.
# 最後にmanual_name_modify_list.txtを削除している理由はAstsearchR_between_COIAS_and_ReCOIASと同じ.
##############################################################################################

set -o pipefail
echo AstsearchR_after_manual begins 2>&1 | tee -a log.txt
echo $? 85 801 > error.txt

photometry_manual_objects.py 2>&1 | tee -a log.txt
match2E.py 2>&1 | tee -a log.txt
change_data_to_mpc_format_manual.py 2>&1 | tee -a log.txt

cat numbered_disp_m.txt karifugo_disp_m.txt unknown_disp_m.txt > disp_m.txt 2>&1 | tee -a log.txt
cat numbered_mpc_m.txt karifugo_mpc_m.txt unknown_mpc_m.txt > mpc_m.txt     2>&1 | tee -a log.txt
cat numbered_all_m.txt karifugo_all_m.txt unknown_all_m.txt > all_m.txt     2>&1 | tee -a log.txt
echo $? 84 805 >> error.txt

sed 's/r2     /r     /g;' mpc_m.txt > tmpmpc1_m.txt   2>&1 | tee -a log.txt
sed 's/i2     /i     /g;' tmpmpc1_m.txt > tmpmpc2.txt 2>&1 | tee -a log.txt
sed 's/r2     /r     /g;' all_m.txt > tmpall1_m.txt   2>&1 | tee -a log.txt
sed 's/i2     /i     /g;' tmpall1_m.txt > tmpall2.txt 2>&1 | tee -a log.txt
echo $? 84 806 >> error.txt

rm tmpmpc1_m.txt tmpall1_m.txt 2>&1 | tee -a log.txt
cat tmpmpc2.txt > mpc_m.txt      2>&1 | tee -a log.txt
cat tmpall2.txt > all_m.txt      2>&1 | tee -a log.txt
echo $? 84 807 >> error.txt

make_mpc4_newall_and_redisp_manual.py 2>&1 | tee -a log.txt

apply_manual_delete_to_redisp.py 2>&1 | tee -a log.txt

cat redisp2.txt redisp_manual.txt | sort -k 1,1 -k 2n,2 > reredisp.txt
echo $? 84 809 >> error.txt

sort -n -o mpc4_m.txt mpc4_m.txt 2>&1 | tee -a log.txt
sort -n -o newall_m.txt newall_m.txt 2>&1 | tee -a log.txt
echo $? 84 810 >> error.txt

if [ -e "manual_name_modify_list.txt" ]; then
	rm manual_name_modify_list.txt
	echo $? 85 811 >> error.txt
fi

echo AstsearchR_after_manual ends 2>&1 | tee -a log.txt

error_handling.py | tee -a log.txt
exit $?
