#!/bin/bash

#S.U made on 2021/7/14
astsearch1Q5.py
match2E.py
mpc1c.py
mpc2c.py
cat numbered_disp_m.txt karifugo_disp_m.txt unknown_disp_m.txt >> disp.txt
#cat numbered_mpc_m.txt karifugo_mpc_m.txt unknown_mpc_m.txt >> mpc.txt
#cat numbered_all_m.txt karifugo_all_m.txt unknown_all_m.txt >> all.txt
#revised S.U 2021.8.27
cat numbered_mpc_m.txt karifugo_mpc_m.txt unknown_mpc_m.txt > mpc_m.txt
cat numbered_all_m.txt karifugo_all_m.txt unknown_all_m.txt > all_m.txt

sed 's/r2     /r     /g;' mpc_m.txt > tmpmpc1_m.txt
sed 's/i2     /i     /g;' tmpmpc1_m.txt > tmpmpc2.txt
sed 's/r2     /r     /g;' all_m.txt > tmpall1_m.txt
sed 's/i2     /i     /g;' tmpall1_m.txt > tmpall2.txt
rm tmpmpc1_m.txt tmpall1_m.txt
cat tmpmpc2.txt >>mpc.txt
cat tmpall2.txt >>all.txt
N=`awk '{print $4}' memo2.txt |sed -e "s/'//g" | sed -e "s/)//g" |uniq `
printf "%06d\n" $N >> memo.txt
