#!/bin/bash
# Timestamp: 2022/12/22 12:00 sugiura
####################################################################
# startsearch2R や astsearch_new などのスクリプトで
# オプション的に指定されたパラメータをparam.txtに書き出すスクリプト.
# パラメータの指定方法や意味の詳細はCOIAS_program_github/README.mdを参照.
# param.txtには
# [パラメータ名] [値]
# の書式で全てのパラメータが書き出される.
# startsearch2R などの実行時に指定されなかったパラメータは,
# 以下に記述してあるデフォルトの値が書き出される.
####################################################################

nd="4" # default value for detection number threshold for moving objects
ar="6" # default value for aparture radius in pixel for photometory
vt="1.5" # default value for velocity threshold to detect moving objects
dm="6" #default value for DETECT_MINAREA, i.e., minimum area for detecting sources at SExtractor
sn="500" #default value for mean source number detected by SExtractor
id="-1" #default value for user id for webCOIAS

for arg in "$@"; do
  case $arg in
    nd=*) nd=${arg#???}                 ;;
    ar=*) ar=${arg#???}                 ;;
    vt=*) vt=${arg#???}                 ;;
	dm=*) dm=${arg#???}                 ;;
	sn=*) sn=${arg#???}                 ;;
	id=*) id=${arg#???}                 ;;
       *) echo "Invalid option" 1>&2    ;;
  esac
done

echo nd $nd >  param.txt
echo ar $ar >> param.txt
echo vt $vt >> param.txt
echo dm $dm >> param.txt
echo sn $sn >> param.txt
echo id $id >> param.txt
