#!/bin/bash
# Time-stamp: <2022/05/21 20:30:00 (JST) sugiura>

nd="4" # default value for detection number threshold for moving objects
ar="6" # default value for aparture radius in pixel for photometory
vt="1.5" # default value for velocity threshold to detect moving objects
dm="6" #default value for DETECT_MINAREA, i.e., minimum area for detecting sources at SExtractor

for arg in "$@"; do
  case $arg in
    nd=*) nd=${arg#???}                 ;;
    ar=*) ar=${arg#???}                 ;;
    vt=*) vt=${arg#???}                 ;;
	dm=*) dm=${arg#???}                 ;;
       *) echo "Invalid option" 1>&2    ;;
  esac
done

echo nd $nd >  param.txt
echo ar $ar >> param.txt
echo vt $vt >> param.txt
echo dm $dm >> param.txt
