#!/bin/bash
#version 2022.5.6 K.S.

set -o pipefail
echo prempsearchC-after begins 2>&1 | tee log.txt
echo $? 45 401 > error.txt

getinfo_karifugo2D.py 2>&1 | tee -a log.txt

#(cat numbered_new2B.txt karifugo_new2B.txt |sort -n >search_astB.txt) <- old statement, we did not use this from 2020/12
#Revised 2020.2.20
#grep -E "^19|^20" karifugo_new2B.txt > karifugo_new2C.txt 
#cat numbered_new2B.txt karifugo_new2C.txt |sort -n > search_astpre.txt
#REVISED 2020.2.2
#Revised 2020.2.20
#sed 's/--/30.0/g;' search_astpre.txt |sed 's/ (1999 19 //g;' |sed 's/ (1981 2 //g;'|sed 's/ - / /g;'> search_astB.txt
#Revised 2022.4.12 KS, I merged the above three statements to make_seach_astB_in_each_directory.py
make_search_astB_in_each_directory.py 2>&1 | tee -a log.txt

echo prempsearchC-after ends 2>&1 | tee -a log.txt

error_handling.py | tee -a log.txt
exit $?
