#!/bin/bash
#version 2022.5.6 K.S.

set -o pipefail

for i in warp*_bin.fits
do
echo $i
t1=$(echo $i|sed "s/.fits/.dat/g")
echo $? 25 205 >> error.txt

source-extractor $i -c ~/.coias/param/default.sex
echo $? 24 206 >> error.txt

echo $t1
cp test.cat $t1
echo $? 24 207 >> error.txt

done
