#!/bin/bash
#Timestamp: 2022/08/04 13:30 sugiura
####################################################################
# SExtractorを用いた光源検出をするスクリプトの本体.
# findsource_auto_thresh_correct.pyでパラメータ調整がなされた後,
# 同スクリプト内からこのスクリプトが呼ばれる.
#
# 入力: マスク後の画像データ warp*_bin.fits
# 出力: 検出された光源のピクセル座標のリスト warp*_bin.dat
# 　　  (書式はファイルを直接見ればわかる)
####################################################################

set -o pipefail

for i in warp*_bin.fits
do
echo $i
t1=$(echo $i|sed "s/.fits/.dat/g")
echo $? 25 205 >> error.txt

source-extractor $i -c default.sex
echo $? 24 206 >> error.txt

echo $t1
cp test.cat $t1
echo $? 24 207 >> error.txt

done
