#!/bin/bash
#Timestamp: 2022/08/04 13:00 sugiura
########################################################
# ビニング・マスク・光源検出などを統括するスクリプト.
# GUI COIASのビニングマスクボタンで叩かれるのはこれ.
# 1. binning.py ビニング
# 2. subm2.py マスク
# 3. findsource_auto_thresh_correct.py 光源検出
# 4. search_precise_orbit_directories.py
#    JPLに問い合わせた精密軌道情報がすでにあるかどうかチェック
########################################################

set -o pipefail
echo startsearch2R begins 2>&1 | tee log.txt
echo $? 25 201 > error.txt

mkparam "$@" 2>&1 | tee -a log.txt
echo $? 25 209 >> error.txt

binning.py 2>&1 | tee -a log.txt

subm2.py 2>&1 | tee -a log.txt

findsource_auto_thresh_correct.py 2>&1 | tee -a log.txt

search_precise_orbit_directories.py 2>&1 | tee -a log.txt

echo startsearch2R ends 2>&1 | tee -a log.txt

error_handling.py | tee -a log.txt
exit $?
